info:
  contact: {}
paths:
  /user/create:
    post:
      consumes:
      - application/json
      description: create user
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
      summary: create exemple
      tags:
      - User
swagger: "2.0"
