# Database
DB_USER: "postgres"
DB_NAME: "postgres"
DB_PASSWORD: "postgres"
DB_HOST: "postgresql-db"
DB_PORT: "5432"

# Server
# API_SERVER_HOST: "localhost"
API_SERVER_PORT: "4200"

# AWS
AWS_REGION: "us-east-1"
