# Database
DB_USER: "postgres"
DB_NAME: "postgres"
DB_PASSWORD: "postgres"
DB_HOST: "postgresql-db"
DB_PORT: "5432"

# Server
# API_SERVER_HOST: "localhost"
API_SERVER_PORT: "4200"
API_FULLCHAIN: "/app/env/certs/cert.pem"
API_PRIVKEY: "/app/env/certs/key.pem"

# AWS
AWS_REGION: "us-east-1"

# AWS Cognito
APP_CLIENT_ID: "4qq70oblk6fem0h2b7ch5iki5s"
USER_PASSWORD_AUTH: "gym-partner-password-auth"